### ISSUE TITLE
Inconsistent use of star suffix in buffer names

### ISSUE THREAD

**Issue by magne-hov** [luismbo/multi-magit#13]
Some of the multi magit buffers do not get a star suffix. The fact that the multi magit buffers start with a star `*` suggests to me that they are meant to be treated like other starred buffers such as `*Messages*` or `*Help*`. The lack of a star suffix causes functions such as `ibuffer-filter-by-starred-name` to not work with them.

Some buffers have a prefix and suffix:

https://github.com/luismbo/multi-magit/blob/8a68380292f82fe38f03f9d3fa5a5c894d84c688/multi-magit.el#L386

https://github.com/luismbo/multi-magit/blob/8a68380292f82fe38f03f9d3fa5a5c894d84c688/multi-magit.el#L544

Whereas these do not have a suffix:

https://github.com/luismbo/multi-magit/blob/8a68380292f82fe38f03f9d3fa5a5c894d84c688/multi-magit.el#L150

https://github.com/luismbo/multi-magit/blob/8a68380292f82fe38f03f9d3fa5a5c894d84c688/multi-magit.el#L608

**Comment by luismbo** [comment]
No idea how that happened. Perhaps magit used that convention in the past and I blindly copied it? 🤷‍♂️ Fixed, thanks.
